name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build
        run: cargo build --release --verbose

      - name: Package
        run: |
          cd target/release
          tar -czf cdtree-mac.tar.gz cdtree

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            target/release/cdtree-mac.tar.gz
